## 1. Backtesting Basics

## 1. Reading data

In [3]:
from tools import ROOT
from tools.readers.lighter import LobReaderRaw, LobReader, TradesReaderRaw, TradesReader

In [4]:
lob_paths = [
    ROOT / f"data/lighter/DOGE/lob/202607{day:02d}/{hour:02d}.parquet"
    for day in range(12, 13)
    for hour in range(0, 10)
]
trades_paths = [
    ROOT / f"data/lighter/DOGE/trades/202607{day:02d}/{hour:02d}.jsonl.zst"
    for day in range(12, 13)
    for hour in range(0, 10)
]

In [5]:
lobs = LobReader(lob_paths).load()

lobs

,sent_ts,recv_ts,ask_px_1,ask_sz_1,ask_px_2,ask_sz_2,ask_px_3,ask_sz_3,ask_px_4,ask_sz_4,...,bid_px_26,bid_sz_26,bid_px_27,bid_sz_27,bid_px_28,bid_sz_28,bid_px_29,bid_sz_29,bid_px_30,bid_sz_30
0,1783814400042000,1783814400143202,0.073109,2052.0,0.073110,5423.0,0.073159,138289.0,0.073161,138289.0,...,0.072406,31397.0,0.072042,31418.0,0.071840,2223.0,0.071637,2408.0,0.071584,566.0
1,1783814400092000,1783814400159075,0.073109,2052.0,0.073110,5423.0,0.073159,138289.0,0.073161,138289.0,...,0.072406,31397.0,0.072042,31418.0,0.071840,2223.0,0.071637,2408.0,0.071584,566.0
2,1783814400394000,1783814400394744,0.073108,5423.0,0.073109,2052.0,0.073159,138289.0,0.073161,138289.0,...,0.072042,31418.0,0.071840,2223.0,0.071637,2408.0,0.071584,566.0,0.071435,2592.0
3,1783814400446000,1783814400448150,0.073108,5423.0,0.073109,2052.0,0.073110,11995.0,0.073159,138289.0,...,0.071232,2777.0,0.071030,2963.0,0.071016,28551.0,0.070827,3148.0,0.070625,3333.0
4,1783814400495000,1783814400495969,0.073107,2053.0,0.073108,5423.0,0.073110,11995.0,0.073159,138289.0,...,0.071435,2592.0,0.071232,2777.0,0.071030,2963.0,0.071016,28551.0,0.070827,3148.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131784,1783850398193000,1783850398194068,0.072920,2057.0,0.072930,11081.0,0.072935,9625.0,0.072947,161000.0,...,0.071854,31496.0,0.071840,2223.0,0.071637,2408.0,0.071435,2592.0,0.071232,2777.0
131785,1783850398445000,1783850398446183,0.072920,2057.0,0.072924,7253.0,0.072930,3831.0,0.072935,9625.0,...,0.071854,31496.0,0.071840,2223.0,0.071637,2408.0,0.071435,2592.0,0.071232,2777.0
131786,1783850398994000,1783850398995611,0.072920,2057.0,0.072927,7251.0,0.072930,3831.0,0.072935,9625.0,...,0.071854,31496.0,0.071840,2223.0,0.071637,2408.0,0.071435,2592.0,0.071232,2777.0
131787,1783850399495000,1783850399496390,0.072920,2057.0,0.072928,7231.0,0.072930,3831.0,0.072935,9625.0,...,0.071854,31496.0,0.071840,2223.0,0.071637,2408.0,0.071435,2592.0,0.071232,2777.0
131788,1783850399996000,1783850399996967,0.072920,2057.0,0.072924,7243.0,0.072930,3831.0,0.072935,9625.0,...,0.071854,31496.0,0.071840,2223.0,0.071637,2408.0,0.071435,2592.0,0.071232,2777.0

In [6]:
for i, line in enumerate(TradesReaderRaw(trades_paths)):
    if i > 1:
        break
    print(line, end="\n\n")

{"channel": "trade:3", "liquidation_trades": [], "nonce": 16701167330, "trades": [{"trade_id": 25128216051, "trade_id_str": "25128216051", "tx_hash": "6b18d5581f0a4e1ec02251c3f4bfc191f6803fe8e161acd53a2ba0b9c5c4b3594afd1f62f74dd73b", "type": "trade", "market_id": 3, "size": "12", "price": "0.072967", "usd_amount": "0.875604", "ask_id": 1125900167761206, "ask_id_str": "1125900167761206", "bid_id": 1407374632065037, "bid_id_str": "1407374632065037", "ask_client_id": 17838144312500, "ask_client_id_str": "17838144312500", "bid_client_id": 198692434804903, "bid_client_id_str": "198692434804903", "ask_account_id": 281474976626278, "bid_account_id": 314661, "is_maker_ask": false, "block_height": 289127576, "timestamp": 1783814431945, "taker_position_size_before": "0", "taker_entry_quote_before": "0.000000", "taker_initial_margin_fraction_before": 1000, "taker_position_sign_changed": true, "maker_fee": 28, "maker_position_size_before": "-630", "maker_entry_quote_before": "46.076940", "maker_initial_margin_fraction_before": 1000, "transaction_time": 1783814431974706}], "type": "update/trade", "receive_timestamp": 1783814431978607}

{"channel": "trade:3", "liquidation_trades": [], "nonce": 16701171026, "trades": [{"trade_id": 25128222058, "trade_id_str": "25128222058", "tx_hash": "cfcad82c3ae7391a851ea6e42fc2260c9fe214b8b56b9484e2954cb0bd0918664c00e18b88ec70f3", "type": "trade", "market_id": 3, "size": "46", "price": "0.072979", "usd_amount": "3.357034", "ask_id": 1125900167761215, "ask_id_str": "1125900167761215", "bid_id": 1407374632065021, "bid_id_str": "1407374632065021", "ask_client_id": 1403010135, "ask_client_id_str": "1403010135", "bid_client_id": 35861102304843, "bid_client_id_str": "35861102304843", "ask_account_id": 103395, "bid_account_id": 314661, "is_maker_ask": false, "block_height": 289127647, "timestamp": 1783814435805, "taker_position_size_before": "-167", "taker_entry_quote_before": "12.425594", "taker_initial_margin_fraction_before": 1000, "maker_fee": 28, "maker_position_size_before": "-618", "maker_entry_quote_before": "45.199284", "maker_initial_margin_fraction_before": 1000, "transaction_time": 1783814435807514}], "type": "update/trade", "receive_timestamp": 1783814435812599}

In [7]:
trades = TradesReader(trades_paths).load()

trades

,receive_timestamp,timestamp,transaction_time,trade_id,type,price,size,is_maker_ask,ask_account_id,bid_account_id,ask_id,bid_id,taker_fee,maker_fee,taker_position_size_before,maker_position_size_before,block_height
0,1783814431978607,1783814431945000,1783814431974706,25128216051,trade,0.072967,12.0,False,281474976626278,314661,1125900167761206,1407374632065037,0,28,0.0,-630.0,289127576
1,1783814435812599,1783814435805000,1783814435807514,25128222058,trade,0.072979,46.0,False,103395,314661,1125900167761215,1407374632065021,0,28,-167.0,-618.0,289127647
2,1783814506021324,1783814505873000,1783814506017892,25128300395,trade,0.073198,2050.0,True,314661,281474976665857,1125900167761553,1407374632064566,280,28,-7320.0,-572.0,289128584
3,1783814506587331,1783814506537000,1783814506583794,25128300726,trade,0.073198,1679.0,False,724009,281474976665857,1125900167761556,1407374632064566,0,40,166066.0,-5270.0,289128589
4,1783814520298975,1783814520284000,1783814520297134,25128313972,trade,0.073213,4159.0,True,415333,100986,1125900167761586,1407374632064503,273,28,-7847.0,5776.0,289128736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,1783849916195145,1783849916077000,1783849916193208,25147382406,trade,0.072950,548.0,False,716824,314233,1125900167879174,1407374631994515,0,28,9981.0,409524.0,289354173
245,1783849933183861,1783849933104000,1783849933181526,25147390629,trade,0.072937,2740.0,False,724009,726314,1125900167879230,1407374631994502,0,32,217808.0,289617.0,289354278
246,1783849933793013,1783849933675000,1783849933790988,25147391065,trade,0.072937,548.0,False,716824,726314,1125900167879238,1407374631994502,0,32,9433.0,292357.0,289354283
247,1783849935793669,1783849935677000,1783849935791558,25147391824,trade,0.072937,548.0,False,716824,726314,1125900167879250,1407374631994502,0,32,8885.0,292905.0,289354294
248,1783850373874485,1783850373754000,1783850373872442,25147589047,trade,0.072883,548.0,False,716824,726314,1125900167880420,1407374631994244,0,32,8337.0,293453.0,289356521