## 1. Backtesting Basics

## 1. Reading data

In [27]:
from analysis.readers import LobReaderRaw, LobReader, TradesReaderRaw, TradesReader

In [37]:
DAYS = 2

lob_paths = [
    f"data/SOL/lob/202604{day:02d}/{hour:02d}.lz4"
    for day in range(1, DAYS + 1)
    for hour in range(0, 24)
]
trades_paths = [
    f"data/SOL/trades/202604{day:02d}/{hour:02d}.lz4"
    for day in range(1, DAYS + 1)
    for hour in range(0, 24)
]

In [39]:
"""
length = 0;

for i, line in enumerate(LobReaderRaw(lob_paths)):
    if i <= 1:
        print(line, end="\n\n")
    length += 1

print(length)
"""

lobs = LobReader(lob_paths).load()

lobs

,time_ms,bid_px_0,bid_sz_0,bid_n_0,bid_px_1,bid_sz_1,bid_n_1,bid_px_2,bid_sz_2,bid_n_2,...,ask_n_16,ask_px_17,ask_sz_17,ask_n_17,ask_px_18,ask_sz_18,ask_n_18,ask_px_19,ask_sz_19,ask_n_19
0,1775001612017,83.141,18.41,1,83.137,0.14,1,83.134,7.11,2,...,1,83.188,27.88,1,83.189,0.14,1,83.193,257.27,1
1,1775001612773,83.141,12.03,1,83.138,99.96,1,83.137,0.14,1,...,1,83.185,26.97,2,83.188,27.88,1,83.189,0.14,1
2,1775001613178,83.141,12.03,1,83.138,99.96,1,83.137,0.14,1,...,1,83.185,26.97,2,83.188,27.88,1,83.189,0.14,1
3,1775001613684,83.150,11.08,1,83.141,12.03,1,83.137,0.14,1,...,1,83.185,9.61,1,83.188,27.88,1,83.189,0.14,1
4,1775001614255,83.150,11.08,1,83.141,12.03,1,83.137,0.14,1,...,1,83.183,0.17,1,83.185,9.61,1,83.188,27.88,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310952,1775174395149,78.901,1133.20,12,78.900,126.76,2,78.898,11.06,2,...,1,78.924,84.26,2,78.925,239.45,2,78.926,207.69,2
310953,1775174395683,78.901,1133.20,12,78.900,126.76,2,78.898,11.06,2,...,1,78.924,84.26,2,78.925,239.45,2,78.926,207.69,2
310954,1775174396239,78.901,358.71,7,78.898,4.54,1,78.897,115.99,1,...,3,78.923,63.36,1,78.924,83.43,1,78.925,316.89,2
310955,1775174396842,78.901,125.98,3,78.895,0.97,2,78.893,61.72,2,...,2,78.922,13.47,2,78.924,83.43,1,78.925,0.14,1
310956,1775174397374,78.895,0.14,1,78.893,55.20,1,78.889,0.14,1,...,1,78.915,49.47,2,78.916,224.99,3,78.917,570.25,3

In [36]:
"""
length = 0

for i, line in enumerate(TradesReaderRaw(trades_paths)):
    if i <= 1:
        print(line, end="\n\n")
    length += 1

print(length)
"""

trades = TradesReader(trades_paths).load()

trades

,time,px,sz,side,crossed,fee,user,dir,startPosition
0,2026-04-01T00:00:04.723000,83.168,12.02,B,False,0.101967,0x69d1652ae43f819e7518f732b2ea6b1a8ad00336,Open Long,2848.60
1,2026-04-01T00:00:04.723000,83.168,12.02,A,True,0.167946,0xc029043cd00b80363130fa058818459a521842a1,Close Long,242.30
2,2026-04-01T00:00:08.242000,83.164,4.14,B,True,0.320886,0xbc75f4b90aafee3d9a6493e852259ff0d4eb0033,Open Long,0.00
3,2026-04-01T00:00:08.242000,83.164,4.14,A,False,-0.003442,0xb4d6fe0f1504a55c65a986ef55b9148a6f0dae7a,Close Long,156.31
4,2026-04-01T00:00:10.392000,83.160,0.68,A,False,0.000000,0x31ca8395cf837de08b24da3f660e77761dfb974b,Open Short,-2756.00
...,...,...,...,...,...,...,...,...,...
285963,2026-04-01T23:59:52.886000,81.157,0.73,B,True,0.021328,0x89a289b2e7436ddb73d00812f9d904d761243ab6,Open Long,0.91
285964,2026-04-01T23:59:53.834000,81.156,9.86,A,True,0.304075,0x43675dfe9ff8351038e0ccc88e31b0ac94b883fe,Open Short,-17.22
285965,2026-04-01T23:59:53.834000,81.156,9.86,B,False,-0.024005,0x5483dd0f8b7d2544a6ac14ba8659988178fd9f4a,Open Long,206.18
285966,2026-04-01T23:59:59.086000,81.152,0.26,A,True,0.009020,0xb7d0e665a00ebc680caeba73b70fad758045798f,Open Short,-11.52
285967,2026-04-01T23:59:59.086000,81.152,0.26,B,False,-0.000632,0xecb63caa47c7c4e77f60f1ce858cf28dc2b82b00,Close Short,-89001.39